# HTTP Server
[server]
	Address     = ":8100"
	ServerAgent = "go-gatewary"
	LogPath     = "/tmp/log/go-gatewary/server"
    AccessLogEnabled = true
    ErrorLogEnabled  = true
    PProfEnabled     = true

# Logger.
[logger]
    Path        = "/tmp/log/go-gatewary"
    Level       = "all"
    Stdout      = false

# Database.
[database]
    link  = "mysql:pibigstar:pibigstar@tcp(106.54.212.69:3306)/go_gateway"
    debug = true
    MaxIdle = 10
    MaxOpen = 50
    MaxLifetime = 30
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/go-gatewary/sql"
        Level  = "all"
        Stdout = true


[cluster]
    ip = "127.0.0.1"
    port = 8088
    ssl_port = 7000